### ISSUE TITLE
broadcast address

### ISSUE THREAD

**Issue by marcobrianza** [hubsif/arduino-dali#4]
hello, how do you send a message to broadcast?

**Comment by hubsif** [comment]
Hi @marcobrianza,

Since a broadcast is the same as sending a command to group address 63 (all bits high), you can do as follows:
```
Dali.sendCmdWait(63, <command>, Dali.DALI_GROUP_ADDRESS);     
```
(Also see [ code at DALI-MQTT project](https://github.com/hubsif/DALI-MQTT-actuator/blob/a05d2ca3358ac2629799b36431babea51a7dd378/Arduino-sketch/DALI-Aktor.ino#L786) as sample.)

Perhaps having a shortcut function for this wouldn't hurt...
